#!/usr/bin/env bash
# Warn-only freshness check for the command-reference derived formats.
#
# The .txt/.html twins of command-reference.md.tmpl and
# windows/command-reference.md are generated by
# scripts/render-command-reference.sh and committed; this hook catches a
# stale commit at apply time. It never fails the apply and never writes —
# regenerating into the source tree here would dirty the clone and break the
# ts-update/ts-rollback clean-clone invariant. The Windows-native sync path
# (scripts/sync-windows.ps1) carries its own equivalent warning.
set -uo pipefail

src_dir="${CHEZMOI_SOURCE_DIR:-$HOME/.local/share/chezmoi}"
renderer="$src_dir/scripts/render-command-reference.sh"
[ -f "$renderer" ] || exit 0

out="$(bash "$renderer" --check 2>&1)" || {
  echo "check-command-reference: generated command-reference twins are out of date:" >&2
  printf '%s\n' "$out" | sed 's/^/  /' >&2
}
exit 0
